name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.14.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71a044f47b1d66d0eec97893f163e5278598d977ee2af2d51171ce0e7b284af8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
