name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.14.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62ec61d5e26c9249567ea261b31d26d79b7de4b996ef7cb2d97ad0828e0e660d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
