name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.14.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53f1559ed0c68f2ea1e3b118d4fc134d0ed806354bce1b212ae6c4c2b794cbb9"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
